指令: team
未加入队伍系统表单标题: 组队系统
未加入队伍系统表单查看可加入队伍按钮: 查看可加入队伍
未加入队伍系统表单创建新队伍按钮: 创建新队伍
创建队伍表单标题: 创建队伍
创建队伍表单输入提示: 请输入队伍名称
服务器所有可加入队伍表单标题: 服务器所有可加入队伍
服务器所有可加入队伍表单提示: 发送申请给队伍
退出队伍表单标题: 退出队伍
退出队伍表单退出按钮: 退出队伍
队伍系统表单标题: 队伍系统
队伍系统查看队伍人数按钮: 查看队伍人数
队伍系统退出队伍按钮: 退出队伍
队长查看队伍邀请按钮: 查看申请列表
队长踢出成员按钮: 踢出成员
成员名单: 成员名单@a队伍
队长邀请函标题: 申请列表
队长踢出玩家表单标题: 踢出玩家
玩家发送申请给队伍: 你已发送请求给队伍@a
队长收到申请消息通知: 队伍收到来自@p的加入请求
加入队伍玩家发送消息: 恭喜加入到@a的队伍
其余玩家发送加入消息: 欢迎新人@p进入了队伍
退出队伍玩家发送消息: 你已经退出队伍
退出队伍消息: 玩家@p已经退出@a